import numpy as np 

aa_3_to_1 = {
    'CYS': 'C', 'ASP': 'D', 'SER': 'S', 'GLN': 'Q', 'LYS': 'K',
    'ILE': 'I', 'PRO': 'P', 'THR': 'T', 'PHE': 'F', 'ASN': 'N', 
    'GLY': 'G', 'HIS': 'H', 'LEU': 'L', 'ARG': 'R', 'TRP': 'W', 
    'ALA': 'A', 'VAL':'V', 'GLU': 'E', 'TYR': 'Y', 'MET': 'M',
}

aa_1_to_3 = {}
for key in aa_3_to_1.keys():
    aa_1_to_3[aa_3_to_1[key]] = key


PARENTAL_ID_TO_ANTIGEN_CHAIN_ID = {
    "A34467":"B",
    "A38781":"A",
    "HER2":"C",
}

PARENTAL_ID_TO_AB_CHAIN_ID = {
    "A34467":"A",
    "A38781":"H",
    "HER2":["A","B"],
}



PARENTAL_ID_TO_AB_SEQ = {
    "A38781":"QVQLVESGGGLVQAGGSLRLSCAASGSVSDTNLMGWYRQAPGKQRDLVASITTGGLRNYVVPVKGRFTISRDNAKKTSYLQMNALKPDDTAVYYCWSRDIFRGNEYWGQGTQVTVSS",
    "A34467":"EVQLVDSGGGLVQPGGSLRLSCAVSGRMFSAYIEGWYRQAPGKPRELIASITSGGNTNYVDSVKDRFTISRDSAKNTVYLQMNSLKPEDTAVYYCNVRDSVRYRDYWGQGTQVTVSS",
    "HER2":"DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGECEVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEP",
}

PARENTAL_ID_TO_AG_SEQ = {
    "HER2":"TQVCTGTDMKLRLPASPETHLDMLRHLYQGCQVVQGNLELTYLPTNASLSFLQDIQEVQGYVLIAHNQVRQVPLQRLRIVRGTQLFEDNYALAVLDNGDPLSPGGLRELQLRSLTEILKGGVLIQRNPQLCYQDTILWKDIFHKNNQLALTLIDTNRSRACHPCSPMCKGSRCWGESSEDCQSLTRTVCAGGCARCKGPLPTDCCHEQCAAGCTGPKHSDCLACLHFNHSGICELHCPALVTYNTDTFESMPNPEGRYTFGASCVTACPYNYLSTDVGSCTLVCPLHNQEVTATQRCEKCSKPCARVCYGLGMEHLREVRAVTSANIQEFAGCKKIFGSLAFLPESFDSNTAPLQPEQLQVFETLEEITGYLYISAWPDSLPDLSVFQNLQVIRGRILHNGAYSLTLQGLGISWLGLRSLRELGSGLALIHHNTHLCFVHTVPWDQLFRNPHQALLHTANRPEDECVGEGLACHQLCARGHCWGPGPTQCVNCSQFLRGQECVEECRVLQGLPREYVNARHCLPCHPECQPQNGSVTCFGPEADQCVACAHYKDPPFCVARCPSIWKFPDEEGACQPCPIN",
    "A38781":"MYDFTNCDFEKIKAAYLSTISKDLITYMSGTVSCSNRPHCLTEIQSLTFNPTAGCASLAKEMFAMKTKAALAIWCPGYSETQINKCLEQVSQLQGLWRRFNRPL",
}
PARENTAL_ID_TO_AG_SEQ["A34467"] = PARENTAL_ID_TO_AG_SEQ["A38781"]


PARENTAL_ID_TO_KD_WITHOUT_MUTATIONS = {
    "A34467":8.44563541960629,
    "A38781":8.647087238943177,
    "HER2":1,
}

HER2_AB_CHAINS = [
    "DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC",
    "EVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEP",
]


# HER2_CDR_3 = "WGGDGFYAMD" # len10, worsk for affinity_data_cdr3.csv (v1 chinnery et al)
HER2_CDR_3 = "SRWGGDGFYAMDY" # len13 for shzz et al data  (201/422 have length 13, are others insertions or deletions??)

# add for shzz v2 constants_shzz 
HER2_CDR_1 = "GFNIKDTY"
HER2_CDR_2 = "IYPTNGYT"

HER2_CDRS_LIST = [HER2_CDR_1, HER2_CDR_2, HER2_CDR_3 ]

HER2_CDR_FIRST_INDEX_LIST = []
HER2_CDR_LAST_INDEX_LIST = [] 
for cdr_seq in HER2_CDRS_LIST:
    first_index = HER2_AB_CHAINS[1].find(cdr_seq)
    last_index = first_index+len(cdr_seq)
    assert cdr_seq == HER2_AB_CHAINS[1][first_index:last_index]
    HER2_CDR_FIRST_INDEX_LIST.append(first_index)
    HER2_CDR_LAST_INDEX_LIST.append(last_index)


# for prev versions that only used CDR3... (before constant_shzz)
HER2_CDR3_FIRST_INDEX = HER2_CDR_FIRST_INDEX_LIST[-1]
HER2_CDR3_LAST_INDEX = HER2_CDR_LAST_INDEX_LIST[-1]

# * Used for prev versions (before constant_shzz) --> only cdr 3 allowed to refine... 
# HER3_CDR_INDEXES = np.arange(HER2_CDR3_FIRST_INDEX , HER2_CDR3_LAST_INDEX).tolist() 
HER3_CDR_INDEXES = [] 
for i in range(3):
    HER3_CDR_INDEXES = HER3_CDR_INDEXES + np.arange(HER2_CDR_FIRST_INDEX_LIST[i], HER2_CDR_LAST_INDEX_LIST[i]).tolist()
PILLBOX_CDR_INDEXES = np.arange(25, 32).tolist() + np.arange(51, 56).tolist() + np.arange(97, 106).tolist()
PARENTAL_ID_TO_CDR_INDEXES = {
    "A34467":(0, PILLBOX_CDR_INDEXES),
    "A38781":(0, PILLBOX_CDR_INDEXES),
    "HER2":(1, HER3_CDR_INDEXES),
}




