import numpy as np 

aa_3_to_1 = {
    'CYS': 'C', 'ASP': 'D', 'SER': 'S', 'GLN': 'Q', 'LYS': 'K',
    'ILE': 'I', 'PRO': 'P', 'THR': 'T', 'PHE': 'F', 'ASN': 'N', 
    'GLY': 'G', 'HIS': 'H', 'LEU': 'L', 'ARG': 'R', 'TRP': 'W', 
    'ALA': 'A', 'VAL':'V', 'GLU': 'E', 'TYR': 'Y', 'MET': 'M',
}

aa_1_to_3 = {}
for key in aa_3_to_1.keys():
    aa_1_to_3[aa_3_to_1[key]] = key


PARENTAL_ID_TO_ANTIGEN_CHAIN_ID = {
    "A34467":"B",
    "A38781":"A",
    "HER2":"C",
}

PARENTAL_ID_TO_AB_CHAIN_ID = {
    "A34467":"A",
    "A38781":"H",
    "HER2":["A","B"],
}



PARENTAL_ID_TO_AB_SEQ = {
    "A38781":"QVQLVESGGGLVQAGGSLRLSCAASGSVSDTNLMGWYRQAPGKQRDLVASITTGGLRNYVVPVKGRFTISRDNAKKTSYLQMNALKPDDTAVYYCWSRDIFRGNEYWGQGTQVTVSS",
    "A34467":"EVQLVDSGGGLVQPGGSLRLSCAVSGRMFSAYIEGWYRQAPGKPRELIASITSGGNTNYVDSVKDRFTISRDSAKNTVYLQMNSLKPEDTAVYYCNVRDSVRYRDYWGQGTQVTVSS",
    "HER2":"DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGECEVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEP",
}

PARENTAL_ID_TO_AG_SEQ = {
    "HER2":"TQVCTGTDMKLRLPASPETHLDMLRHLYQGCQVVQGNLELTYLPTNASLSFLQDIQEVQGYVLIAHNQVRQVPLQRLRIVRGTQLFEDNYALAVLDNGDPLSPGGLRELQLRSLTEILKGGVLIQRNPQLCYQDTILWKDIFHKNNQLALTLIDTNRSRACHPCSPMCKGSRCWGESSEDCQSLTRTVCAGGCARCKGPLPTDCCHEQCAAGCTGPKHSDCLACLHFNHSGICELHCPALVTYNTDTFESMPNPEGRYTFGASCVTACPYNYLSTDVGSCTLVCPLHNQEVTATQRCEKCSKPCARVCYGLGMEHLREVRAVTSANIQEFAGCKKIFGSLAFLPESFDSNTAPLQPEQLQVFETLEEITGYLYISAWPDSLPDLSVFQNLQVIRGRILHNGAYSLTLQGLGISWLGLRSLRELGSGLALIHHNTHLCFVHTVPWDQLFRNPHQALLHTANRPEDECVGEGLACHQLCARGHCWGPGPTQCVNCSQFLRGQECVEECRVLQGLPREYVNARHCLPCHPECQPQNGSVTCFGPEADQCVACAHYKDPPFCVARCPSIWKFPDEEGACQPCPIN",
    "A38781":"MYDFTNCDFEKIKAAYLSTISKDLITYMSGTVSCSNRPHCLTEIQSLTFNPTAGCASLAKEMFAMKTKAALAIWCPGYSETQINKCLEQVSQLQGLWRRFNRPL",
}
PARENTAL_ID_TO_AG_SEQ["A34467"] = PARENTAL_ID_TO_AG_SEQ["A38781"]


PARENTAL_ID_TO_KD_WITHOUT_MUTATIONS = {
    "A34467":8.44563541960629,
    "A38781":8.647087238943177,
    "HER2":1,
}

HER2_AB_CHAINS = [
    "DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC",
    "EVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEP",
]


# HER2_CDR_3 = "WGGDGFYAMD" # len10, worsk for affinity_data_cdr3.csv (v1 chinnery et al)
HER2_CDR_3 = "SRWGGDGFYAMDY" # len13 for shzz et al data  (201/422 have length 13, are others insertions or deletions??)


HER2_CDR3_FIRST_INDEX = HER2_AB_CHAINS[1].find(HER2_CDR_3)
HER2_CDR3_LAST_INDEX = HER2_CDR3_FIRST_INDEX+len(HER2_CDR_3)
assert HER2_CDR_3 == HER2_AB_CHAINS[1][HER2_CDR3_FIRST_INDEX:HER2_CDR3_LAST_INDEX]

HER3_CDR_INDEXES = np.arange(HER2_CDR3_FIRST_INDEX , HER2_CDR3_LAST_INDEX).tolist()
PILLBOX_CDR_INDEXES = np.arange(25, 32).tolist() + np.arange(51, 56).tolist() + np.arange(97, 106).tolist()
PARENTAL_ID_TO_CDR_INDEXES = {
    "A34467":(0, PILLBOX_CDR_INDEXES),
    "A38781":(0, PILLBOX_CDR_INDEXES),
    "HER2":(1, HER3_CDR_INDEXES),
}
